name: Test and Dist

on:
    push:
        branches:
            - develop
            - main
        tags:
            - "v*"
    pull_request:
        branches:
            - main

permissions:
    contents: write # This is required to create a release

concurrency:
    group: "test-and-dist"
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup corepack
              run: corepack enable

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: yarn

            - name: Test, lint and format
              run: yarn all

    dist:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: yarn

            # Setup git config to allow pushes
            - name: Setup git config
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"

            - name: Build the distribution
              run: yarn dist

              # Authenticate using GITHUB_TOKEN and push changes
            - name: Push changes
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: git push
